apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      run: mynginx-pod
  template:
    metadata:
      labels:
        run: mynginx-pod
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
